function addError(){
    return alertify.success('新增成功');
}

function updateSuccess(){
    return alertify.success('更新成功');
}